### ISSUE TITLE
Failed to discover the definition of function EnvironmentMap?

### ISSUE THREAD

**Issue by rain2050** [weberhen/learning_indoor_lighting#3]
Hello! I am very confused, I can't solve this problem with "from envmap import EnvironmentMap" in net.py,  and I hope to get your help. Thank you very much!

**Comment by weberhen** [comment]
Hi,
EnvironmentMap comes from skylibs, one of the dependencies listed in the README.md. Make sure you've installed skylibs (by cloning the repo and then `python setup.py install`). I have also included an extra step to make openexr work with python, which is simply to install openexr dependencies: `sudo apt-get install openexr libopenexr-dev`. If you still have trouble please let me know.
