### ISSUE TITLE
where is the indoor_hdr image

### ISSUE THREAD

**Issue by fnzhan** [weberhen/learning_indoor_lighting#4]
The test.py also doesn't work as below:

Visdom available at: http://localhost:8097
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    hdr_image_handler = HDRImageHandler(opt.mean_std, perform_scale_perturbation=False)
  File "build/bdist.linux-x86_64/egg/learning_indoor_lighting/tools/hdr_image.py", line 21, in __init__
TypeError: super() argument 1 must be type, not classobj

**Comment by fnzhan** [comment]
@weberhen

**Comment by weberhen** [comment]
Hi @fnzhan,
one sample HDR image can now be found in https://github.com/weberhen/learning_indoor_lighting/blob/master/learning_indoor_lighting/Datasets/indoor_hdr/valid/output-01-31-9C4A9060-9C4A9060_Panorama_hdr_inpainted-result_000.exr

More HDR images can be downloaded here: http://indoor.hdrdb.com/

About your error, did you change the code in any way? I just installed and run the code in a fresh computer and all went fine.

**Comment by fnzhan** [comment]
Hi, @weberhen 
Thanks for your help. The issue is caused by Python2. Python3 works well.

**Comment by weberhen** [comment]
glad it worked :) 

if you have any questions do not hesitate to ask.
