### ISSUE TITLE
Links to the pre-trained model and the dataset 'ERR_EMPTY_RESPONSE'

### ISSUE THREAD

**Issue by MayuOshima** [weberhen/learning_indoor_lighting#6]
Hello ! Thanks for your great work !
However, when I click the links to the pre-trained model and the dataset, it shows ERR_EMPTY_RESPONSE.
Could you please give valid links ?
Thank you !

**Comment by weberhen** [comment]
Hi!!
Thats weird, they are working on my side. Can you try copying the link and pasting it manually on another tab of your browser to see if it works?

**Comment by weberhen** [comment]
please let me know if you got the data, otherwise we will find another solution
