### ISSUE TITLE
Hi, could you publish the code for building the HDR dataset described in the article

### ISSUE THREAD

**Issue by heartxkl** [weberhen/learning_indoor_lighting#7]

**Comment by weberhen** [comment]
Hi @heartxkl,

Im really sorry but I dont have that code anymore. If you want to do it by yourself, I suggest to take the pfm files (the panoramas depth map): http://indoor.hdrdb.com/UlavalHDR-depth.tar.gz convert it to a ply with the HDR color from the panorama assigned to each point. From there you can use mitsuba for example to place a spherical camera inside the point cloud at different positions and render new viewpoints for each pano.

**Comment by heartxkl** [comment]
Thanks ~
