### ISSUE TITLE
The link to the pre-trained illumination predictor models

### ISSUE THREAD

**Issue by taoxinhao13** [weberhen/learning_indoor_lighting#9]
Hello, your work is excellent, but your link is dead. Can you please give me a new link to the pre-trained illumination predictor models?

**Comment by weberhen** [comment]
Hi @taoxinhao13 !

Unfortunately that server is under maintenance and its the only place I kept that data, so once its back up and running (should be back in a week or two) I can ping you here :)

**Comment by weberhen** [comment]
Hello!

Sorry for the late reply. The links are working again.

Thank you.

**Comment by huynhtruc0309** [comment]
Hi @weberhen. The links are dead again, can you check them?

**Comment by weberhen** [comment]
Sorry my mistake, I updated them elsewhere not here, now they are correct.
